language: python
python:
  - "3.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install .
# command to run tests, e.g. python setup.py test
script: nosetests
